spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mydatabase?createDatabaseIfNotExist=true&characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: qwe123qwe456